from typing import Iterable, List, Optional, Sequence, Tuple, Union

Fragment = Tuple[str, str]


def figs_to_html_fragments(figs: Iterable[Tuple[str, object]]) -> List[Fragment]:
    fragments: List[Fragment] = []
    for name, fig in figs:
        try:
            frag = fig.to_html(full_html=False, include_plotlyjs="cdn")
        except Exception:
            frag = f"<div><h3>{name}</h3><p>(chart unavailable)</p></div>"
        fragments.append((name, frag))
    return fragments


def build_report_html(
    title: str,
    fragments: Sequence[Fragment],
    metadata: Optional[List[str]] = None,
    footer_text: str = "",
) -> str:
    meta_html = ""
    if metadata:
        meta_html = (
            "<div style='margin-bottom:12px; font-size:0.95em; color:#444;'>"
            + " | ".join(metadata)
            + "</div>"
        )
    body = [
        "<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>",
        "<style>@media print{@page{size:A4;margin:20mm}} body{font-family:Helvetica,Arial,sans-serif;color:#222;padding:18px} .report-title{font-size:22px;font-weight:700;margin-bottom:6px}.report-section{page-break-inside:avoid;margin-bottom:18px}</style>",
        "</head><body>",
        f"<div class='report-title'>{title}</div>",
        meta_html,
    ]
    for name, frag in fragments:
        body.append(
            f"<div class='report-section'><h2 style='font-size:16px;color:#333;margin-bottom:6px'>{name}</h2>"
        )
        body.append(frag)
        body.append("</div>")
    body.append(
        f"<div style='font-size:10px;color:#666;margin-top:18px'>Generated by Burkeanomics Simulator — {footer_text}</div>"
    )
    body.append("</body></html>")
    return "\n".join(body)


def render_pdf_with_playwright(html_bytes_or_str: Union[str, bytes]) -> bytes:
    try:
        from playwright.sync_api import sync_playwright
    except Exception:
        raise RuntimeError(
            "Playwright is not installed. Install with `pip install playwright` and run `playwright install chromium`."
        )

    html = (
        html_bytes_or_str
        if isinstance(html_bytes_or_str, str)
        else html_bytes_or_str.decode("utf-8")
    )
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.set_content(html, wait_until="networkidle")
        pdf_bytes = page.pdf(format="A4", print_background=True)
        browser.close()
    return pdf_bytes


def normalize_pdf_filename(universe_name: str, default_name: str = "universe.pdf") -> str:
    safe_name = (universe_name or default_name).strip()
    if not safe_name:
        safe_name = default_name
    safe_name = safe_name.replace(' ', '_')
    return safe_name if safe_name.lower().endswith('.pdf') else f"{safe_name}.pdf"
